"""
Main Application Entry Point
Orchestrates the SN Report Automation workflow.
"""

import sys
import logging
from pathlib import Path
from src.config import get_config
from src.utils import setup_logging
from src.excel_reader import ExcelReader
from src.metrics import MetricsCalculator
from src.ppt_updater import PowerPointUpdater
from src.chart_generator import ChartGenerator


class ReportAutomation:
    """Main application class."""

    def __init__(self):
        """Initialize application."""
        self.config = get_config()
        self.logger = setup_logging(
            self.config.logs_dir,
            logging.INFO
        )
        self.logger.info("=" * 60)
        self.logger.info(f"{self.config.get('app_name')} v{self.config.get('version')}")
        self.logger.info("=" * 60)

    def run_full_workflow(self, excel_file, template_file=None, output_name='report.pptx'):
        """
        Run complete automation workflow.
        
        Args:
            excel_file: Input Excel file path
            template_file: PowerPoint template path
            output_name: Output PowerPoint filename
            
        Returns:
            True if successful
        """
        try:
            self.logger.info("Starting full workflow...")

            # Step 1: Read Excel
            self.logger.info("Step 1: Reading Excel file...")
            reader = ExcelReader(self.config.input_dir)
            wb = reader.load_workbook(excel_file)
            if not wb:
                self.logger.error("Failed to load Excel file")
                return False

            sheet_names = reader.get_sheet_names(wb)
            self.logger.info(f"Found sheets: {sheet_names}")

            if not sheet_names:
                self.logger.error("No sheets found in Excel file")
                return False

            data = reader.read_sheet_as_dict(wb, sheet_names[0])
            self.logger.info(f"Loaded {len(data)} records")

            # Step 2: Calculate metrics
            self.logger.info("Step 2: Calculating metrics...")
            calculator = MetricsCalculator()
            summary = calculator.create_summary(data, [
                {'type': 'count', 'label': 'Total Records'},
                {'type': 'sum', 'column': list(data[0].keys())[0], 'label': 'Sum'},
                {'type': 'average', 'column': list(data[0].keys())[0], 'label': 'Average'},
            ])
            self.logger.info(f"Calculated {len(summary['kpis'])} KPIs")

            # Step 3: Generate charts
            self.logger.info("Step 3: Generating charts...")
            charts_dir = self.config.charts_dir
            chart_gen = ChartGenerator(charts_dir)
            self.logger.info(f"Charts saved to: {charts_dir}")

            # Step 4: Update PowerPoint
            self.logger.info("Step 4: Updating PowerPoint...")
            ppt = PowerPointUpdater()

            if template_file:
                ppt.load_template(template_file)
            else:
                ppt.create_blank()

            if ppt.presentation:
                ppt.add_slide_with_title("Report Summary", "Generated by SN Automation")

                for kpi_name, kpi_data in summary['kpis'].items():
                    kpi_value = kpi_data.get('value', 'N/A')
                    ppt.add_text_box(
                        len(ppt.presentation.slides) - 1,
                        1, len(ppt.presentation.slides) * 0.5,
                        8, 1,
                        f"{kpi_name}: {kpi_value}"
                    )

                output_path = self.config.output_dir / output_name
                if ppt.save_presentation(output_path):
                    self.logger.info(f"Report saved: {output_path}")
                else:
                    self.logger.error("Failed to save presentation")
                    return False

            self.logger.info("✓ Workflow completed successfully!")
            return True

        except Exception as e:
            self.logger.error(f"Workflow error: {str(e)}", exc_info=True)
            return False

    def list_input_files(self):
        """List all Excel files in input directory."""
        reader = ExcelReader(self.config.input_dir)
        files = reader.get_excel_files()
        return files

    def run_minimal_test(self):
        """Run minimal test to verify modules."""
        self.logger.info("Running minimal test...")
        try:
            reader = ExcelReader(self.config.input_dir)
            self.logger.info("[OK] Excel reader initialized")

            calculator = MetricsCalculator()
            self.logger.info("[OK] Metrics calculator initialized")

            ppt = PowerPointUpdater()
            ppt.create_blank()
            self.logger.info("[OK] PowerPoint updater initialized")

            charts = ChartGenerator(self.config.charts_dir)
            self.logger.info("[OK] Chart generator initialized")

            self.logger.info("[OK] All modules functional!")
            return True
        except Exception as e:
            self.logger.error(f"Test failed: {str(e)}", exc_info=True)
            return False


def main():
    """Main entry point."""
    app = ReportAutomation()

    input_files = app.list_input_files()
    if not input_files:
        app.logger.warning("No Excel files in input directory")
        app.logger.info("Please add Excel files to: input/")
    else:
        app.logger.info(f"Found {len(input_files)} Excel file(s)")

    app.run_minimal_test()


if __name__ == '__main__':
    main()
